version: '3'

services:
  firefly:
    image: fireflyiii/core:latest
    restart: unless-stopped
    ports:
     - 8080:8080
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=firefly
      - APP_KEY=r9EVFH8ppyNmyBhS9TvaqGeC9NV9SX2v
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=firefly
      - MARIADB_DATABASE=firefly
      - MARIADB_USER=firefly
      - MARIADB_PASSWORD=firefly
    volumes:
     - mariadb-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb-data:
